#! /bin/sh

bash ~/.config/bspwm/autostart.sh

bspc monitor -d 1 2 3 4 5 6 7 8 9

# bspc config focused_border_color "#FFFFFF"
bspc config normal_border_color "#020202"
bspc config border_width 50
bspc config borderless_monocle true

# bspc config active_border_color "#bd93f9"
# bspc config presel_feedback_color "#6272a4"


bspc config window_gap 100

bspc config border_width         2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a firefox desktop='^1' follow=on
bspc rule -a TelegramDesktop desktop='^2' follow=on
bspc rule -a "YouTube Music" desktop='^8' follow=on
